In [9]:
import tensorflow as tf
model = tf.keras.models.load_model('digit_model')

In [10]:
from ipycanvas import Canvas, hold_canvas
import ipywidgets as widgeats
from ipywidgets import TwoByTwoLayout
from math import pi

In [11]:
canvas = Canvas(width=280,height=280, sync_image_data=True)

In [12]:
started_drawing = False

def on_mouse_down(x, y):
    global started_drawing
    started_drawing = True
canvas.on_mouse_down(on_mouse_down)

def on_mouse_move(x, y):
    global started_drawing
    if started_drawing:
        with hold_canvas(canvas):
            canvas.fill_arc(x,y,10,0,2*pi)
    else:
        return
        
def on_mouse_up(x, y):
    global started_drawing
    started_drawing = False
    
canvas.on_mouse_down(on_mouse_down)
canvas.on_mouse_move(on_mouse_move)
canvas.on_mouse_up(on_mouse_up)

In [13]:
button = widgets.Button(description='Clear')

def button_clicked(_):
    canvas.clear()
    
button.on_click(button_clicked)

In [14]:
import numpy as np
import matplotlib.pyplot as plt

def get_canvas_image():
    canvas_rgb = canvas.get_image_data()
    canvas_gray = canvas_rgb[...,3]
    canvas_gray_reduced = canvas_gray[::10,::10]
    return canvas_gray_reduced
    
def predict_number(*args):
    #plt.subplot(1, 2, 1)
    #plt.clf()
    canvas_image = get_canvas_image()
    prediction = model.predict(np.array([canvas_image,]))
    print(prediction)
    #labels = [0,1,2,3,4,5,6,7,8,9]
    #plt.subplot(1, 2, 1)
    #plt.bar(labels, height=prediction[0])
    #plt.xticks(labels,labels);
    #plt.subplot(1, 2, 2)
    #plt.imshow(canvas_image)
    print(f"Predicted number: {np.argmax(prediction)} ")

In [15]:
predict_button = widgets.Button(
    description='Predict',
    disabled=False,
    button_style='info', # 'success', 'info', 'warning', 'danger' or ''
    tooltip='Click me',
)
predict_button.on_click(predict_number)
TwoByTwoLayout(top_left=canvas, top_right=button, bottom_right=predict_button)

TwoByTwoLayout(children=(Canvas(height=280, layout=Layout(grid_area='top-left'), sync_image_data=True, width=2…

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Predicted number: 3 
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Predicted number: 1 
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
Predicted number: 8 
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Predicted number: 0 
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
Predicted number: 2 
