In [72]:
import tensorflow as tf

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [73]:
model = tf.keras.Sequential([tf.keras.layers.Flatten(),
                             tf.keras.layers.Dense(1024, activation='relu'),
                             tf.keras.layers.Dense(10, activation='softmax')])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [74]:
model.fit(x_train, y_train, metrics=['accuracy'], epochs=5)

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1855 - accuracy: 0.9441
Epoch 2/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0754 - accuracy: 0.9770
Epoch 3/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0489 - accuracy: 0.9840
Epoch 4/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0351 - accuracy: 0.9889
Epoch 5/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0244 - accuracy: 0.9918


In [70]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s


[0.07531416416168213, 0.9800999760627747]

In [195]:
from ipycanvas import Canvas, hold_canvas
import ipywidgets as widgets
from ipywidgets import TwoByTwoLayout
from math import pi

In [95]:
canvas = Canvas(width=280,height=280, sync_image_data=True)

In [165]:
started_drawing = False

def on_mouse_down(x, y):
    global started_drawing
    started_drawing = True
canvas.on_mouse_down(on_mouse_down)

def on_mouse_move(x, y):
    global started_drawing
    if started_drawing:
        with hold_canvas(canvas):
            canvas.fill_arc(x,y,10,0,2*pi)
    else:
        return
        
def on_mouse_up(x, y):
    global started_drawing
    started_drawing = False
    
canvas.on_mouse_down(on_mouse_down)
canvas.on_mouse_move(on_mouse_move)
canvas.on_mouse_up(on_mouse_up)

In [185]:
button = widgets.Button(description='Clear')

def button_clicked(_):
    canvas.clear()
    
button.on_click(button_clicked)

In [226]:
import numpy as np
import matplotlib.pyplot as plt

def get_canvas_image():
    canvas_rgb = canvas.get_image_data()
    canvas_gray = canvas_rgb[...,3]
    canvas_gray_reduced = canvas_gray[::10,::10]
    return canvas_gray_reduced
    
def predict_number(*args):
    #plt.subplot(1, 2, 1)
    #plt.clf()
    canvas_image = get_canvas_image()
    prediction = model.predict(np.array([canvas_image,]))
    print(prediction)
    #labels = [0,1,2,3,4,5,6,7,8,9]
    #plt.subplot(1, 2, 1)
    #plt.bar(labels, height=prediction[0])
    #plt.xticks(labels,labels);
    #plt.subplot(1, 2, 2)
    #plt.imshow(canvas_image)
    print(f"Predicted number: {np.argmax(prediction)} ")

In [227]:
predict_button = widgets.Button(
    description='Predict',
    disabled=False,
    button_style='info', # 'success', 'info', 'warning', 'danger' or ''
    tooltip='Click me',
)
predict_button.on_click(predict_number)
TwoByTwoLayout(top_left=canvas, top_right=button, bottom_right=predict_button)

TwoByTwoLayout(children=(Canvas(height=280, image_data=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x01\x18\x…

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
Predicted number: 1 
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Predicted number: 0 
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 2.3003166e-21 0.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00]]
Predicted number: 9 
